### ISSUE TITLE
Downtime not cleared after reconnect

### ISSUE THREAD

**Issue by asbachb** [ZencashOfficial/nodetracker#81]
I had a situation where the nodetracker lost connection to the tracking server but reconnected 3s afterwards. An exception was created but it was not closed automatically. The tracker needed to be restarted manually to close down the exception:

```
Aug 20 11:13:10 zencash-super-95612 node[20912]: 2018-08-20 09:13:10 UTC -- No connection to xns4.eu
Aug 20 11:13:11 zencash-super-95612 node[20912]: 2018-08-20 09:13:11 UTC -- Server send reconnect.
Aug 20 11:13:11 zencash-super-95612 node[20912]: 2018-08-20 09:13:11 UTC -- Connected to server xns4.eu. Initializing...
Aug 20 11:13:14 zencash-super-95612 node[20912]: 2018-08-20 09:13:14 UTC -- Authenticated. Nice to see you connected again.
Aug 20 11:13:14 zencash-super-95612 node[20912]: 2018-08-20 09:13:14 UTC -- Updated server list
Aug 20 11:13:14 zencash-super-95612 node[20912]: 2018-08-20 09:13:14 UTC -- Stats: send initial stats.
Aug 20 11:13:14 zencash-super-95612 node[20912]: 2018-08-20 09:13:14 UTC -- Saved servers=xns4.eu,xns1.eu,xns2.eu,xns3.eu,xns1.na,xns2.na,xns3.na,xns4.na
Aug 20 11:13:14 zencash-super-95612 node[20912]: 2018-08-20 09:13:14 UTC -- Stats received by xns4.eu
[...]
-- Reboot --
[...]
Aug 20 11:28:33 zencash-super-95612 node[1106]: 2018-08-20 09:28:33 UTC -- Down time logged. See server.
```

**Comment by ADumaine** [comment]
The Downtime may have been due to the reboot or created prior to that reconnect (would need to see logs).  
Any disconnects under 45 seconds are ignored by the tracking server.   
A subsequent stat check will also trigger a Downtime (it may not have run before the reboot).

The secure node tracking servers will be updated in the next few days and have additional checks for closing Downtimes sooner.  

I will close this for now, but please reopen or create ticket in the help desk if this is an issue after the upcoming server and node updates.
